### ISSUE TITLE
Crashes upon startup 1.18.2

### ISSUE THREAD

**Issue by DTX3** [dima-dencep/blur-forge#2]
Can't start MC with this mod installed. 

Forge: 40.2.0
Version: 1.18.2
Mod version: blur-2.4.2+mc1.18.2-build.3

[Crash log](https://pastebin.com/Lp095yNR)

**Comment by Miroslav-Novotny64** [comment]
Same thing here

**Comment by dima-dencep** [comment]
Fixed
