### ISSUE TITLE
[Bug] Game hangs on world creation or load. [1.18.2]

### ISSUE THREAD

**Issue by JENOVAAbsolute** [dima-dencep/blur-forge#3]
As the title says. It does not crash to desktop. You spawn, but the game renders nothing, and you can not do anything at all. I have to force close the game.

Forge version: 40.2.1

Image:
![Bug](https://user-images.githubusercontent.com/60951301/233565749-44bf315b-acd5-428b-9dd0-8b93d6f211c8.png)

Logs:
[latest.log](https://github.com/dimadencep/Blur-Forge/files/11293132/latest.log)
[debug.log](https://github.com/dimadencep/Blur-Forge/files/11293134/debug.log)

**Comment by dima-dencep** [comment]
Fixed
