### ISSUE TITLE
not working on forge 1.20.1

### ISSUE THREAD

**Issue by hopemik** [dima-dencep/blur-forge#7]
not sure what the issue is. i have cloth config 11.1.06 forge and blur 3.1.0 but the blur does not show up in game

**Comment by vinnyg0621** [comment]
wait so you're not gonna fix it??

**Comment by dima-dencep** [comment]
Fix what? I checked it and it worked for me, there is no further information here so I have closed this issue

**Comment by vinnyg0621** [comment]
it did? it didn't for me...
